[workspace.package]
version = "4.6.0"

[workspace]
resolver = "2"
members = [
    "render-conjure",
    "witchcraft-server",
    "witchcraft-server-config",
    "witchcraft-server-ete",
    "witchcraft-server-macros",
]

[patch.crates-io]
exponential-decay-histogram = { git = "https://github.com/sfackler/exponential-decay-histogram", branch = "exemplars" }
witchcraft-metrics = { git = "https://github.com/palantir/witchcraft-rust-logging", branch = "exemplars" }
